# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Test Suites
    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install yarn
        run: npm install -g yarn
        working-directory: server
      
      - name: Install dependencies
        run: yarn install
        working-directory: server
        
      - name: Run unit tests
        run: yarn test
        working-directory: server
